name: Deploy

on:
  push:
    branches: [main]
  release:
    types: [created]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Java JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Empaquetar JAR (Shaded)
        run: mvn -B package --no-transfer-progress

      - name: Subir artefacto de despliegue
        uses: actions/upload-artifact@v4
        with:
          name: estante-shaded
          path: target/estante-*-shaded.jar
